name: Automations

on: [push, pull_request]

jobs:
  run:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1

    - name: Run npm install
      run: npm install

    - name: Run cypress
      run: npm run cypress:run
