name: Design System Automations

on: [push]

jobs:
  run:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1

    - name: Cypress run
      uses: cypress-io/github-action@v1
      with:
        start: npm run storybook
        wait-on: http://localhost:6020
